Golden_Leaf/views/product/forms.py
import sqlalchemy
from flask_admin.contrib.sqla.fields import QuerySelectField
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import StringField, SubmitField, DecimalField, BooleanField, SelectField
from wtforms.validators import DataRequired, Length, NumberRange, Regexp, ValidationError

from Golden_Leaf.models import Category, Product, db


def enabled_categories():
    return Category.query


class NewProductForm(FlaskForm):
    category = SelectField('Categoria', coerce=int, choices=[])
    description = StringField('Descrição', validators=[Length(min=3, max=128,message="Descrição deve ter entre 3 e 128 caracteres."), Regexp(
        '^([A-Za-z0-9\u00C0-\u00D6\u00D8-\u00f6\u00f8-\u00ff\s\.\-]*)$')])
    unit_cost = DecimalField('Preço', validators=[DataRequired(message="Produto precisa ter um preço."), 
                                                             NumberRange(min=0.5, max=100.0,message="Preço do produto precisa estar entre R$ 0.5 e R$ 100.00")])
    code = StringField('Código',
                       validators=[DataRequired(), Length(min=9, max=13, 
                                                          message="Código do produto precisa ter entre 9 e 13 dígitos.")])
    submit = SubmitField('Salvar')

    def validate_code(self, code):
        if Product.query.filter_by(code=code.data).first():
            raise ValidationError('Código de produto já registrado.')


class SearchProductForm(FlaskForm):
    description = StringField('Palavra chave')
    code = StringField('Código do produto')
    submit = SubmitField('Buscar')


class UpdateProductForm(FlaskForm):
    categories = QuerySelectField('Categorias',
                                  query_factory=enabled_categories, allow_blank=False,
                                  get_label='title', get_pk=lambda c: c.id,
                                  blank_text=u'Selecione uma categoria...')

    description = StringField('Descrição', validators=[Length(min=3, max=64), Regexp(
        '^([A-Za-z0-9\u00C0-\u00D6\u00D8-\u00f6\u00f8-\u00ff\s\.\-]*)$')])

    unit_cost = DecimalField('Preço', validators=[NumberRange(min=0.5, max=100.0)])
    code = StringField('Código', render_kw={'disabled': ''})
    is_available = BooleanField("Está disponível")   
    submit = SubmitField('Salvar')

Golden_Leaf/views/product/__init__.py
from flask import Blueprint

blueprint_product = Blueprint('blueprint_product', __name__)

Golden_Leaf/views/product/routes.py
import os
import secrets

from PIL import Image
from flask import render_template, redirect, flash, url_for, request, current_app
from flask_breadcrumbs import register_breadcrumb
from flask_login import login_required

from Golden_Leaf.models import Product, db, Category
from Golden_Leaf.views.product import blueprint_product
from Golden_Leaf.views.product.forms import NewProductForm, SearchProductForm, UpdateProductForm


def view_category_dlc(*args, **kwargs):
    id = request.view_args['id']
    p = Product.query.get(id)
    return [{'text': p.description}]


@blueprint_product.route('/product', methods=['GET'])
@register_breadcrumb(blueprint_product, '.', 'Produtos')
def get_products():
    page = request.args.get('page', 1, type=int)
    products = Product.query.order_by(Product.description).paginate(page=page, per_page=10)
    return render_template('product/list.html', all_products=products)


@blueprint_product.route('/product/available/list', methods=['GET'])
@register_breadcrumb(blueprint_product, '.available_products', 'Produtos em falta')
def available_products():
    page = request.args.get('page', 1, type=int)
    products = Product.query.filter_by(is_available=False).order_by(Product.description).paginate(page=page, per_page=10)
    return render_template('product/list.html', all_products=products)


@blueprint_product.route('/product/new', methods=['GET', 'POST'])
@register_breadcrumb(blueprint_product, '.new_product', 'Novo Produto')
@login_required
def new_product():
    form = NewProductForm()
    form.category.choices = [(category.id, category.title) for category in
                             Category.query.order_by(Category.title).all()]

    if form.validate_on_submit():
        category = Category.query.filter_by(id=form.category.data).one()
        db.session.add(Product(form.category.data,
                               form.description.data,
                               form.unit_cost.data,
                               form.code.data))

        db.session.commit()
        flash(form.description.data + ' inserido com sucesso!', 'success')
        return redirect(url_for('blueprint_product.get_products'))
    return render_template('product/new.html', form=form)


@blueprint_product.route('/product/search', methods=["GET", 'POST'])
@register_breadcrumb(blueprint_product, '.search_product', 'Busca de Produto')
def search_product():
    page = request.args.get('page', 1, type=int)
    form = SearchProductForm()
    products = None
    term = None
    if form.validate_on_submit():
        if form.description.data is not "":
            term = form.description.data
            products = Product.query.filter(Product.brand.like('%' + term + '%')).paginate(page=page,
                                                                                           per_page=10)
        elif form.code.data is not "":
            term = form.code.data
            products = Product.query.filter_by(code=term).paginate(page=page, per_page=10)

        if not products:
            flash('Produto algum encontrado', 'warning')
            return redirect(url_for('blueprint_product.search_product'))
        else:
            flash('Mostrando todos os produtos com "{}" encontrados'.format(term), 'info')
            return render_template('product/list.html', all_products=products)

    return render_template('product/search.html', form=form)


@blueprint_product.route('/product/<int:id>/update', methods=["GET", 'POST'])
@register_breadcrumb(blueprint_product, '.id', '', dynamic_list_constructor=view_category_dlc)
@login_required
def update_product(id):
    product = Product.query.filter_by(id=id).one()
    form = UpdateProductForm(categories=product.category)
    if form.validate_on_submit():
        product.category = form.categories.data
        product.description = form.description.data
        product.unit_cost = form.unit_cost.data
        product.is_available = form.is_available.data
        db.session.add(product)
        db.session.commit()
        flash('Produto atualizada com sucesso.', 'success')
        return redirect(url_for('blueprint_product.update_product', id=product.id))
    elif request.method == 'GET':
        form.description.data = product.description
        form.unit_cost.data = product.unit_cost
        form.code.data = product.code
        form.is_available.data = product.is_available
    image_file = url_for('static', filename='product_pic/' + product.image_file)
    return render_template('product/edit.html', form=form, image_file=image_file)

Golden_Leaf/templates/product/edit.html
{% extends "base.html" %}
{% block page_content %}

<div class="form-container">
    <form action="" method="POST">
        {{ form.csrf_token }}
        {{ form.hidden_tag() }}
        <div class="row">
            <div class="col-25">
                {{ form.categories.label(class="label") }}
            </div>
            <div class="col-75">
                {{form.categories(class="form")}}
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                {{ form.description.label(class="label") }}
            </div>
            <div class="col-75">
                {{form.description(class="form")}}
                {% if form.description.errors %}
                <div class="invalid-feedback">
                    {% for error in form.description.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-25">
                {{ form.unit_cost.label(class="label") }}
            </div>
            <div class="col-75">
                {{form.unit_cost(class="form")}}
                {% if form.unit_cost.errors %}
                <div class="invalid-feedback">
                    {% for error in form.unit_cost.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-25">
                {{ form.code.label(class="label") }}
            </div>
            <div class="col-75">
                {{form.code(class="form")}}
                {% if form.code.errors %}
                <div class="invalid-feedback">
                    {% for error in form.code.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-25">
                {{ form.is_available.label(class="label") }}
            </div>
            <div class="col-75">
                {{form.is_available(class="form")}}
            </div>
        </div>

        <div class="row">
            <div class="col-25">

            </div>
            <div class="col-75">
                {{form.submit(class="btn btn-default")}}
            </div>
        </div>

    </form>
</div>

{% endblock %}

Golden_Leaf/templates/product/list.html
{% extends "base.html" %}
{% block page_content %}
<div class="container">

    <div>
        <a class="btn btn-primary" href="{{ url_for('blueprint_product.new_product') }}">
            Novo
        </a>
        <a class="btn btn-default" href="{{ url_for('blueprint_product.search_product') }}">
            Buscar
        </a>

    </div>

    <div class="table-responsive">
        <table>
            <caption><h4>Produtos</h4></caption>
            <thead>
                <tr>
                    <th>Descrição</th>
                    <th>R$</th>
                    <th>Status</th>
                    <th>Código</th>
                </tr>
            </thead>

            <tbody>
                {% for product in all_products.items %}
                <tr>
                    <td>{{ product.description }}</td>
                    <td>{{ product.unit_cost }}</td>
                    {% if product.is_available %}
                    <td>disponível</td>
                    {% else %}
                    <td>indisponível</td>
                    {% endif %}
                    <td>{{ product.code }}</td>

                    <td align="center">
                        <a class="btn btn-primary" href="{{ url_for('blueprint_product.update_product',id=product.id) }}">
                            Editar
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="pagination">
        {% for page_number in all_products.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {% if page_number %}
        {% if all_products.page == page_number %}
        <a href="{{ url_for('blueprint_product.get_products',page=page_number) }}">{{ page_number }}</a>
        {% else %}
        <a href="{{ url_for('blueprint_product.get_products',page=page_number) }}">{{ page_number }}</a>
        {% endif %}
        {% else %}
        ...
        {% endif %}
        {% endfor %}    
    </div>
</div>
{% endblock %}

Golden_Leaf/templates/product/new.html
{% extends "base.html" %}
{% block page_content %}

<div class="form-container">
    <form action="" method="POST">
        {{ form.csrf_token }}       
        <div class="row">
            <div class="col-25">
                {{ form.category.label(class="label") }}
            </div>
            <div class="col-75">
                {{form.category(class="form")}}
                {% if form.category.errors %}
                <div class="invalid-feedback">
                    {% for error in form.category.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-25">
                {{ form.description.label(class="label") }}
            </div>
            <div class="col-75">
                {{form.description(class="form")}}
                {% if form.description.errors %}
                <div class="invalid-feedback">
                    {% for error in form.description.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-25">
                {{ form.unit_cost.label(class="label") }}
            </div>
            <div class="col-75">
                {{form.unit_cost(class="form")}}
                {% if form.unit_cost.errors %}
                <div class="invalid-feedback">
                    {% for error in form.unit_cost.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-25">
                {{ form.code.label(class="label") }}
            </div>
            <div class="col-75">
                {{form.code(class="form")}}
                {% if form.code.errors %}
                <div class="invalid-feedback">
                    {% for error in form.code.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-25">
                
            </div>
            <div class="col-75">
                {{form.submit(class="btn btn-default")}}
            </div>
        </div>

    </form>
</div>

{% endblock %}

Golden_Leaf/templates/product/search.html
{% extends "base.html" %}
{% block page_content %}

<div class="form-container">
    <form action="" method="POST">
        {{ form.csrf_token }}
        {{ form.hidden_tag() }}
       
        <div class="row">
            <div class="col-25">
                {{ form.description.label(class="label") }}
            </div>
            <div class="col-75">
                {{form.description(class="form")}}
            </div>
        </div>

       
        <div class="row">
            <div class="col-25">
                {{ form.code.label(class="label") }}
            </div>
            <div class="col-75">
                {{form.code(class="form")}}
            </div>
        </div>

        <div class="row">
            <div class="col-25">
                
            </div>
            <div class="col-75">
                {{form.submit(class="btn btn-default")}}
            </div>
        </div>

    </form>
</div>

{% endblock %}