Golden_Leaf/views/category/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Regexp


class CategoryForm(FlaskForm):
    title = StringField('Título', validators=[DataRequired(), Regexp(
        '^([A-Za-z\u00C0-\u00D6\u00D8-\u00f6\u00f8-\u00ff\s\/\-\.]*)$',
        0,
        'O nome da categoria deve conter somente letras')])
    submit = SubmitField('Salvar')


class SearchCategoryForm(FlaskForm):
    title = StringField('Título', validators=[DataRequired(), Regexp(
        '^([A-Za-z\u00C0-\u00D6\u00D8-\u00f6\u00f8-\u00ff\s\/\-\.]*)$',
        0,
        'O nome da categoria deve conter somente letras')])
    submit = SubmitField('Buscar')

Golden_Leaf/views/category/__init__.py
# A blueprint needs to be a package. That's why all folders needs to have a __init__.py
from flask import Blueprint

blueprint_category = Blueprint('blueprint_category', __name__)

Golden_Leaf/views/category/routes.py
from flask import render_template, redirect, url_for, request, flash
from flask_breadcrumbs import register_breadcrumb
from flask_login import login_required

from Golden_Leaf import db
from Golden_Leaf.views.category import blueprint_category
from Golden_Leaf.views.category.forms import CategoryForm, SearchCategoryForm
from Golden_Leaf.models import Category, Product
from Golden_Leaf.views.product.forms import NewProductForm


def view_category_dlc(*args, **kwargs):
    id = request.view_args['id']
    c = Category.query.get(id)
    return [{'text': c.title}]


@blueprint_category.route("/category", methods=['GET'])
@register_breadcrumb(blueprint_category, '.', 'Categorias')
def get_categories():
    page = request.args.get('page', 1, type=int)
    categories = Category.query.order_by(Category.title).paginate(page=page, per_page=10)
    return render_template('category/list.html', categories=categories)


@blueprint_category.route("/category/new", methods=['GET', 'POST'])
@register_breadcrumb(blueprint_category, '.new_category', 'Nova Categoria')
@login_required
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        db.session.add(Category(form.title.data))
        db.session.commit()
        flash(form.title.data + ' inserido com sucesso!', 'success')
        return redirect(url_for('blueprint_category.get_categories'))
    return render_template('category/form.html', form=form)


@blueprint_category.route("/category/search", methods=['GET', 'POST'])
@register_breadcrumb(blueprint_category, '.search_category', 'Busca de Categoria')
def search_category():
    page = request.args.get('page', 1, type=int)
    form = SearchCategoryForm()
    if form.validate_on_submit():
        # Finding names with “form.name.data” in them:
        categories = Category.query.filter(Category.title.like('%' + form.title.data + '%')) \
            .paginate(page=page, per_page=10)
        if not categories:
            flash('Nenhum categoria {} encontrada'.format(form.title.data), 'warning')
            return redirect(url_for('blueprint_category.search_category'))
        else:
            flash('Mostrando categeria(s) encontrada(s) com nome: {}'.format(form.title.data), 'info')
            return render_template('category/list.html', categories=categories)

    return render_template('category/form.html', form=form)


@blueprint_category.route('/category/<int:id>/update', methods=['GET', 'POST'])
@register_breadcrumb(blueprint_category, '.id', '.update_category', dynamic_list_constructor=view_category_dlc)
@login_required
def update_category(id):
    form = CategoryForm()
    category = Category.query.get_or_404(id)
    if form.validate_on_submit():
        category.title = form.title.data
        db.session.add(category)
        db.session.commit()
        flash('Categoria alterada com sucesso!', 'success')
        return redirect(url_for('blueprint_category.get_categories'))
    elif request.method == 'GET':
        form.title.data = category.title
    return render_template('category/form.html', form=form)


@blueprint_category.route('/category/<int:id>/product')
@register_breadcrumb(blueprint_category, '.id', '', dynamic_list_constructor=view_category_dlc)
def products_of(id):
    category = Category.query.get_or_404(id)
    page = request.args.get('page', 1, type=int)
    products = Product.query.filter_by(category=category).order_by(Product.description).paginate(page, per_page=10)
    return render_template('category/productsof.html', category=category, all_products=products)


@blueprint_category.route('/category/<int:id>/product/new', methods=['GET', 'POST'])
@register_breadcrumb(blueprint_category, '.id', '', dynamic_list_constructor=view_category_dlc)
@login_required
def new_product(id):
    form = NewProductForm()
    category = Category.query.filter_by(id=id).one()
    form.category.choices = [(category.id, category.title)]

    if form.validate_on_submit():
        db.session.add(Product(category.id,
                               form.description.data,
                               form.unit_cost.data,
                               form.code.data))

        db.session.commit()
        flash(form.description.data + ' inserido com sucesso!', 'success')
        return redirect(url_for('blueprint_category.products_of', id=category.id))
    return render_template('product/new.html', form=form)

Golden_Leaf/templates/category/form.html
{% extends "base.html" %}
{% block page_content %}

<div class="form-container">
    <form action="" method="POST">
        {{ form.csrf_token }}
        {{ form.hidden_tag() }}
        <div class="row">
            <div class="col-25">
                {{ form.title.label(class="label") }}
            </div>
            <div class="col-75">
                {{form.title(class="form")}}
                {% if form.title.errors %}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="col-25">

            </div>
            <div class="col-75">
                {{form.submit(class="btn btn-default")}}
            </div>
        </div>

    </form>
</div>

{% endblock %}

Golden_Leaf/templates/category/list.html
{% extends "base.html" %}
{% block page_content %}
<div class="container">
    <div>

        <div>
            <a class="btn btn-primary" href="{{ url_for('blueprint_category.new_category') }}">
                Nova
            </a>
            <a class="btn btn-default" href="{{ url_for('blueprint_category.search_category') }}">
                Buscar
            </a>

        </div>

    </div>

    <div class="table-responsive">
        <table>
            <caption><h4>Categorias</h4></caption>
            <thead>
                <tr>
                    <th>Nome</th>
                </tr>
            </thead>

            <tbody>
                {% for category in categories.items %}
                <tr>
                    <td>{{ category.title }}</td>

                    <td>
                        <div class="group-button">
                            <a class="btn btn-primary" href="{{ url_for('blueprint_category.update_category',id=category.id) }}">
                                Editar
                            </a>
                            <a class="btn btn-default" href="{{ url_for('blueprint_category.products_of',id=category.id) }}">
                                Ver produtos
                            </a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="pagination">
        {% for page_number in categories.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {% if page_number %}
        {% if categories.page == page_number %}
        <a
           href="{{ url_for('blueprint_category.get_categories',page=page_number) }}">{{ page_number }}</a>
        {% else %}
        <a
           href="{{ url_for('blueprint_category.get_categories',page=page_number) }}">{{ page_number }}</a>
        {% endif %}
        {% else %}
        ...
        {% endif %}
        {% endfor %}
    </div>
</div>


{% endblock %}

Golden_Leaf/templates/category/productsof.html
{% extends "base.html" %}
{% block title %}Produtos{% endblock %}
{% block page_content %}
<div class="container">
    <div class="row">
        <div class="col col-xs-6 text-right">
            <a href="{{ url_for('blueprint_category.new_product',id=category.id) }}"
               class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span>
                Adicionar produto
            </a>
            <a href="{{ url_for('blueprint_product.search_product') }}"
               class="btn btn-default">
                <span class="glyphicon glyphicon-search"></span>
                Buscar
            </a>

        </div>

    </div>

    <div>
        <table>
            <caption><h4>Produtos da categoria '{{ category.title }}'</h4></caption>
            <thead>
                <tr>
                    <th>Descrição</th>
                    <th>R$</th>
                    <th>Status</th>
                    <th>Código</th>
                </tr>
            </thead>

            <tbody>
                {% for product in all_products.items %}
                <tr>
                    <td>{{ product.description }}</td>
                    <td>{{ product.unit_cost }}</td>
                    {% if product.is_available %}
                    <td>disponível</td>
                    {% else %}
                    <td>indisponível</td>
                    {% endif %}
                    <td>{{ product.code }}</td>

                    <td align="center">
                        <a href="{{ url_for('blueprint_product.update_product',id=product.id) }}"
                           class="btn btn-primary">
                            <i class="glyphicon glyphicon-pencil"></i> Editar
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="panel-footer p-0">
        {% for page_number in all_products.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {% if page_number %}
        {% if all_products.page == page_number %}
        <a class="btn btn-info mb-4"
           href="{{ url_for('blueprint_product.get_products',page=page_number) }}">{{ page_number }}</a>
        {% else %}
        <a class="btn btn-outline-info mb-4"
           href="{{ url_for('blueprint_product.get_products',page=page_number) }}">{{ page_number }}</a>
        {% endif %}
        {% else %}
        ...
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}