Golden_Leaf/views/order/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, SelectField
from wtforms.ext.sqlalchemy.fields import QuerySelectField

from Golden_Leaf.models import Client, Clerk


def enabled_clients():
    return Client.query


def enabled_clerks():
    return Clerk.query


class SearchOrderForm(FlaskForm):
    clerks = QuerySelectField('Atendentes',
                              query_factory=enabled_clerks, allow_blank=True,
                              get_label='name', get_pk=lambda a: a.id,
                              blank_text=u'Selecione uma atendente...')

    clients = QuerySelectField('Clientes',
                               query_factory=enabled_clients, allow_blank=True,
                               get_label='name', get_pk=lambda c: c.id,
                               blank_text=u'Selecione um cliente...')

    # date = DateField("Data")
    status = SelectField("Status", choices=[('PAGO', 'Pago'), ('PENDENTE', 'Pendente')])
    submit = SubmitField('Buscar')

Golden_Leaf/views/order/__init__.py
from flask import Blueprint

blueprint_order = Blueprint('blueprint_order', __name__)

Golden_Leaf/views/order/routes.py
from flask import render_template, current_app, request, redirect, url_for, flash, jsonify
from flask_breadcrumbs import register_breadcrumb
from flask_login import login_required, current_user
from sqlalchemy import func
from Golden_Leaf import db
from Golden_Leaf.models import Order, Client, Item
from Golden_Leaf.views.order import blueprint_order
from Golden_Leaf.views.order.forms import SearchOrderForm
import jwt
from datetime import datetime,timedelta

def view_client_dlc(*args, **kwargs):
    id = request.view_args['id']
    c = Client.query.get(id)
    return [{'text': c.name}]


def view_order_dlc(*args, **kwargs):
    id = request.view_args['id']
    c = Order.query.get(id)
    return [{'text': "renan"}]


@blueprint_order.route('/order/client/<int:id>', methods=['GET'])
@blueprint_order.route('/order', defaults={'id': None}, methods=['GET'])
@register_breadcrumb(blueprint_order, '.', 'Pedidos')
def get_orders(id):
    page = request.args.get('page', 1, type=int)
    if id is not None:
        orders = Order.query \
            .filter_by(client_id=id) \
            .order_by(Order.date.desc()) \
            .paginate(page=page, per_page=10)
        return render_template('order/client_orders.html', orders=orders, client_id=id)
    orders = Order.query.order_by(Order.date.desc()).paginate(page=page, per_page=10)
    return render_template('order/list.html', orders=orders)


@blueprint_order.route('/client/<int:id>/order/new', methods=["GET", 'POST'])
@register_breadcrumb(blueprint_order, '.id', '', dynamic_list_constructor=view_client_dlc)
@login_required
def new_order(id):
    client = Client.query.get_or_404(id)
    token = get_token(client.id, current_user.id)
    return render_template('order/new.html', token=token)


@blueprint_order.route('/order/<int:id>/items', methods=['GET'])
# @register_breadcrumb(blueprint_order, '.id', '',
# dynamic_list_constructor=view_order_dlc)
@login_required
def items_order(id):
    order = Order.query.get_or_404(id)
    page = request.args.get('page', 1, type=int)
    all_items = Item.query.filter_by(order=order).paginate(page, per_page=10)
    return render_template('order/items.html', order_items=all_items)


@blueprint_order.route('/order/search', methods=["GET", 'POST'])
@register_breadcrumb(blueprint_order, '.search_order', 'Busca de Pedido')
def search_order():
    page = request.args.get('page', 1, type=int)
    form = SearchOrderForm()
    if form.validate_on_submit():
        client = form.clients.data
        clerk = form.clerks.data        
        orders = None
        if clerk is not None:
            if client is not None:
                orders = Order.query.filter_by(client=client, clerk=clerk).paginate(page=page,
                                                                                                   per_page=10)
            else:
                orders = Order.query.filter_by(clerk=clerk).paginate(page=page,
                                                                                    per_page=10)

        elif client is not None:
            orders = Order.query.filter_by(client=client).paginate(page=page,
                                                                                  per_page=10)

        if orders:
            flash('Pedido algum encontrado', 'warning')
            return redirect(url_for('blueprint_order.search_order'))
        else:
            flash('Mostrando todos os pedidos encontrados', 'success')
            return render_template('order/list.html', orders=orders)

    return render_template("order/search.html", form=form)



def get_token(client_id, clerk_id, expires_in=25):
    secret = current_app.config['SECRET_KEY']
    payload = {'client_id': client_id,
               'clerk_id': clerk_id,
               'exp': datetime.utcnow() + timedelta(minutes=expires_in)}
    token = jwt.encode(payload, secret)
    return token.decode('UTF-8')

Golden_Leaf/templates/order/client_orders.html
{% extends "base.html" %}
{% block title %}Pedidos{% endblock %}
{% block page_content %}
<div class="container">
    <div class="row">

        <div>

            <a href="{{ url_for('blueprint_order.search_order') }}" class="btn btn-primary">
                <i class="glyphicon glyphicon glyphicon-search"></i>
                <span>Buscar</span>
            </a>

            <a href="{{ url_for('blueprint_payment.new_payment',id=client_id) }}" class="btn btn-primary">
                <i class="glyphicon glyphicon-euro"></i>
                <span>Pagar</span>
            </a>

        </div>

    </div>

    <div class="panel-body">
        <table class="table table-striped table-responsive table-bordered">
            <caption><h4>Pedidos</h4></caption>
            <thead>
                <tr>
                    <th>Comprado em</th>
                    <th>Cliente</th>
                    <th>Atendente</th>
                    <th>Valor R$</th>

                </tr>
            </thead>

            <tbody>
                {% for order in orders.items %}
                <tr>
                    <td>{{ order.date.strftime('%d/%m/%Y %H:%M:%S') }}</td>
                    <td>{{ order.client.name }}</td>
                    <td>{{ order.clerk.name }}</td>
                    <td>{{ order.total }}</td>



                    <td align="center">

                        <a href="{{ url_for('blueprint_order.items_order',id=order.id) }}"
                           class="btn btn-default">
                            <i class="glyphicon glyphicon-list-alt" aria-hidden="true"></i>
                            <span>Itens</span>
                        </a>

                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="pagination">
        {% for page_number in orders.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {% if page_number %}
        {% if orders.page == page_number %}
        <a href="{{ url_for('blueprint_order.get_orders',page=page_number) }}">{{ page_number }}</a>
        {% else %}
        <a href="{{ url_for('blueprint_order.get_orders',page=page_number) }}">{{ page_number }}</a>
        {% endif %}
        {% else %}
        ...
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

Golden_Leaf/templates/order/items.html
{% extends "base.html" %}
{% block page_content %}

<div class="container">
    <table>
        <caption><h4>Lista de itens</h4></caption>
        <thead>
            <tr>
                <th>Descrição</th>
                <th>Quantidade</th>
                <th>Preço Unitátio</th>
                <th>Preto Total</th>
            </tr>
        </thead>

        <tbody>
            {% for item in order_items.items %}
            <tr>
                <td>{{ item.product.description }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.product.unit_cost }}</td>
                <td>{{ item.extended_cost }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div>
    {% for page_number in order_items.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
    {% if page_number %}
    {% if order_items.page == page_number %}
    <a class="btn btn-info mb-4"
       href="{{ url_for('blueprint_order.get_orders',page=page_number) }}">{{ page_number }}</a>
    {% else %}
    <a class="btn btn-outline-info mb-4"
       href="{{ url_for('blueprint_order.get_orders',page=page_number) }}">{{ page_number }}</a>
    {% endif %}
    {% else %}
    ...
    {% endif %}
    {% endfor %}
</div>

{% endblock %}

Golden_Leaf/templates/order/list.html
{% extends "base.html" %}
{% block page_content %}
<div class="container">
    <div>

        <a href="{{ url_for('blueprint_order.search_order') }}" class="btn btn-primary">
            <span class="glyphicon glyphicon-search"></span>
            Buscar pedido
        </a>

    </div>

    <div class="table-responsive">
        <table>
            <caption><h4>Pedidos</h4></caption>
            <thead>
                <tr>
                    <th>Comprado em</th>
                    <th>Cliente</th>
                    <th>Atendente</th>
                    <th>Valor R$</th>
                </tr>
            </thead>

            <tbody>
                {% for order in orders.items %}
                <tr>
                    <td>{{ order.date.strftime('%d/%m/%Y %H:%M:%S') }}</td>
                    <td>{{ order.client.name }}</td>
                    <td>{{ order.clerk.name }}</td>
                    <td>{{ order.total }}</td>


                    <td align="center">

                        <a href="{{ url_for('blueprint_order.items_order',id=order.id) }}"
                           class="btn btn-default">
                            <i class="glyphicon glyphicon-list-alt" aria-hidden="true"></i>
                            <span>Itens</span>
                        </a>

                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="pagination">
        {% for page_number in orders.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {% if page_number %}
        {% if orders.page == page_number %}
        <a href="{{ url_for('blueprint_order.get_orders',page=page_number) }}">{{ page_number }}</a>
        {% else %}
        <a href="{{ url_for('blueprint_order.get_orders',page=page_number) }}">{{ page_number }}</a>
        {% endif %}
        {% else %}
        ...
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

Golden_Leaf/templates/order/new.html
{% extends "base.html" %}
{% block page_content %}

<div id="messageView" class="alert alert-warning">
    <!-- Message will be inserted here dinamicly-->
</div>
<div class="container">
    <div class="row">
        <div class="col-75">
            <div>
                <button type="button" class="btn btn-primary" id="save-items-btn">
                    <i class="glyphicon glyphicon-floppy-disk"></i>
                    <span>Salvar</span>
                </button>
            </div>
            <!-- Table will be inserted here dinamicly-->
            <div class="table-responsive" id="itemsView">

            </div>

        </div>

        <div class="col-25">
            <div class="tabs">
                <input type="radio" id="tabmanual" name="tab" checked="checked">
                <label class="tab-label" for="tabmanual">Manual</label>
                <div class="tab">
                    <form action="" id="manual-form" method="POST">
                        <div id="categoriesView">
                            <!-- Select will be inserted here dinamicly-->
                        </div>

                        <div id="productsView">
                            <!-- Select will be inserted here dinamicly-->
                        </div>

                        <div class="row">
                            <div class="col-25">
                                <label class="label" for="unit_cost_manual_form">Preço</label>
                            </div>
                            <div class="col-75">
                                <input class="form" disabled type="text" id="unit_cost_manual_form">
                            </div>

                        </div>

                        <div class="row">
                            <div class="col-25">
                                <label class="label" for="quantity_manual_form">Quantidade</label>
                            </div>
                            <div class="col-75">
                                <input type="number" placeholder="1,00" name="price" min="0.01" value="1" step="0.01"
                                       class="form" id="quantity_manual_form" required="">
                            </div>
                        </div>
                        <div>
                            <div class="col-25">

                            </div>
                            <div class="col-75">
                                <button type="button" class="btn btn-primary" id="add-item-btn-manual-form">
                                    Adicionar
                                </button>
                            </div>

                        </div>
                    </form>
                </div>

                <input type="radio" id="tabutomatic" name="tab">
                <label class="tab-label" for="tabutomatic">Automatico</label>
                <div class="tab">
                    <form action="" method="POST">
                        <div class="row">
                            <div class="col-25">
                                <label class="label" for="product_code_automatic_form">Código</label>
                            </div>
                            <div class="col-75">
                                <input class="form" type="text" id="product_code_automatic_form" size="13" maxlength="13">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-25">
                                <label class="label" for="description_automatic_form">Descrição</label>
                            </div>
                            <div class="col-75">
                                <input disabled type="text" class="form" id="description_automatic_form">
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-25">
                                <label class="label" for="unit_cost_automatic_form">Preço</label>
                            </div>
                            <div class="col-75">
                                <input disabled type="text" class="form" id="unit_cost_automatic_form">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-25">
                                <label class"label" for="quantity_automatic_form">Quantidade</label>
                            </div>
                            <div class="col-75">
                                <input class="form" type="number" placeholder="1.00" name="price" min="0.01" value="1" step="0.01"
                                       id="quantity_automatic_form" required="">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-25">

                            </div>
                            <div class="col-75">
                                <button type="button" class="btn btn-default" id="search-product-btn-automatic-form">
                                    Buscar
                                </button>
                                <button type="button" class="btn btn-primary" id="add-product-btn-automatic-form">
                                    Adicionar
                                </button>
                            </div>

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>



    <script type="text/javascript">
        localStorage.setItem('token', "{{token}}")
    </script>
    <script src="{{ url_for('static', filename='jquery-3.4.0.min.js') }}" type="text/javascript"></script>







    <!--<script src="{{ url_for('static',filename='order_table.js') }}"></script>-->

    <script src="{{ url_for('static', filename='js/models/Item.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/models/Items.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/models/Category.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/models/Categories.js') }}" type="text/javascript"></script>


    <script src="{{ url_for('static', filename='js/models/PartialProduct.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/models/Product.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/models/Products.js') }}" type="text/javascript"></script>

    <script src="{{ url_for('static', filename='js/views/View.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/views/ProductView.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/views/CategoryView.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/views/ItemView.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/views/MessageView.js') }}" type="text/javascript"></script>

    <script src="{{ url_for('static', filename='js/decorators/domInject.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/decorators/throttle.js') }}" type="text/javascript"></script>

    <script src="{{ url_for('static', filename='js/services/HandlerFunction.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/services/CategoryService.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/services/ProductService.js') }}" type="text/javascript"></script>

    <script src="{{ url_for('static', filename='js/controllers/OrderController.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/app.js') }}" type="text/javascript"></script>

</div>
{% endblock %}

Golden_Leaf/templates/order/search.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Buscar{% endblock %}
{% block page_content %}


<div class="col-md-4 col-md-offset-4">  
    <div class="panel panel-info">
        <div class="panel-heading">
        <h4>Buscar pedido</h4>    
        </div>
        <div class="panel-body">
            <form action="" method="POST">
                {{ form.csrf_token }}
                {{ form.hidden_tag() }}
                {{ wtf.quick_form(form) }}
            </form>
        </div>    
        
    </div>
</div>

{% endblock %}